# Centering Matrix

In [ ]:
import numpy as np

In [ ]:
n = 10

In [ ]:
v = np.random.randn(n)
v

array([ 0.49234789, -1.12657372,  0.66244315, -0.43349988,  1.61794714,
       -1.3777605 , -0.0457128 ,  1.38101907,  0.44490397, -0.74489082])

In [ ]:
v.mean()

0.08702235030983897

In [ ]:
v_c = v - v.mean()
v_c

array([ 0.40532553, -1.21359607,  0.5754208 , -0.52052223,  1.53092479,
       -1.46478285, -0.13273515,  1.29399672,  0.35788162, -0.83191317])

In [ ]:
cm = np.identity(n) - np.ones((n,n))/n
cm

array([[ 0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9]])

In [ ]:
np.matmul(cm, v)

array([ 0.40532553, -1.21359607,  0.5754208 , -0.52052223,  1.53092479,
       -1.46478285, -0.13273515,  1.29399672,  0.35788162, -0.83191317])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c8a1762a-62b2-46cf-95c0-ea77984dacfd' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>