# Node Statistics on Graph

In [ ]:
import numpy as np

# Centrality

In [ ]:
node_ct = 5

In [ ]:
adj_mat_rnd = np.random.randint(2, size=(node_ct, node_ct))
np.fill_diagonal(adj_mat_rnd, 0)
adj_mat_rnd = np.floor((adj_mat_rnd + adj_mat_rnd.T)/2)
adj_mat_rnd

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linalg.eig(adj_mat)

(array([ 2.17008649,  0.31110782, -1.        , -1.4811943 ,  0.        ]),
 array([[ 5.22720726e-01,  3.68160356e-01, -7.07106781e-01,
         -3.02028137e-01,  0.00000000e+00],
        [ 5.22720726e-01,  3.68160356e-01,  7.07106781e-01,
         -3.02028137e-01,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  1.00000000e+00],
        [ 2.81845199e-01, -8.15224745e-01,  1.90125264e-16,
         -5.05936655e-01,  0.00000000e+00],
        [ 6.11628457e-01, -2.53622791e-01, -8.43014807e-18,
          7.49390492e-01,  0.00000000e+00]]))

In [ ]:
e_init = np.ones(node_ct)
e_init

array([1., 1., 1., 1., 1.])

In [ ]:
np.matmul(adj_mat, e_init)

array([2., 2., 0., 1., 3.])

In [ ]:
e_i = e_init.copy()

for i in range(5):
    e_i = np.matmul(adj_mat, e_i)
    # e_i = e_i/np.linalg.norm(e_i)
    print(e_i.shape)
    print(f"{i}: {e_i}")


(5,)
0: [2. 2. 0. 1. 3.]
(5,)
1: [5. 5. 0. 3. 5.]
(5,)
2: [10. 10.  0.  5. 13.]
(5,)
3: [23. 23.  0. 13. 25.]
(5,)
4: [48. 48.  0. 25. 59.]


In [ ]:
def power_iteration(A, num_simulations: int):
    # Ideally choose a random vector
    # To decrease the chance that our vector
    # Is orthogonal to the eigenvector
    b_k = np.random.rand(A.shape[1])

    for _ in range(num_simulations):
        # calculate the matrix-by-vector product Ab
        b_k1 = np.dot(A, b_k)

        # calculate the norm
        b_k1_norm = np.linalg.norm(b_k1)

        # re normalize the vector
        b_k = b_k1 / b_k1_norm

    return b_k



In [ ]:
power_iteration(np.array([[0.5, 0.5], [0.2, 0.8]]), 100)

array([0.70710678, 0.70710678])

In [ ]:
power_iteration(adj_mat, 500)

array([0.52272073, 0.52272073, 0.        , 0.2818452 , 0.61162846])

In [ ]:
adj_florentine = np.array(
    [
        []
    ]
)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c8a1762a-62b2-46cf-95c0-ea77984dacfd' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>