# Some Simple PyTorch Tricks

In [ ]:
import torch

## sum

In [ ]:
rdn_tensor = torch.randn(2,2)
rdn_tensor

tensor([[ 1.1040, -0.1249],
        [ 0.2907,  0.3172]])

In [ ]:
rdn_tensor.sum(0)

tensor([1.3946, 0.1923])

In [ ]:
rdn_tensor.sum(-1)

tensor([0.9790, 0.6079])

In [ ]:
rdn_tensor.sum(0, keepdim=True)

tensor([[1.3946, 0.1923]])

## parameters

In [ ]:
pararmeters_linear = torch.nn.Linear(2,1)
pararmeters_linear

Linear(in_features=2, out_features=1, bias=True)

In [ ]:
pararmeters_linear_weights, pararmeters_linear_biases = pararmeters_linear.parameters()

In [ ]:
pararmeters_linear_weights

Parameter containing:
tensor([[ 0.0198, -0.0294]], requires_grad=True)

In [ ]:
pararmeters_linear_biases

Parameter containing:
tensor([0.4163], requires_grad=True)

## nonzero

In [ ]:
rdn_tensor

tensor([[ 1.1040, -0.1249],
        [ 0.2907,  0.3172]])

In [ ]:
rdn_tensor.nonzero()

tensor([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]])

## view

In [ ]:
rdn_tensor.view(4,-1)

tensor([[ 1.1040],
        [-0.1249],
        [ 0.2907],
        [ 0.3172]])

## ...

In [ ]:
rdn_tensor[...]

tensor([[ 1.1040, -0.1249],
        [ 0.2907,  0.3172]])

In [ ]:
rdn_tensor[..., None]

tensor([[[ 1.1040],
         [-0.1249]],

        [[ 0.2907],
         [ 0.3172]]])

In [ ]:
rdn_tensor.size()

torch.Size([2, 2])

In [ ]:
rdn_tensor[...].size()

torch.Size([2, 2])

In [ ]:
rdn_tensor[..., None].size()

torch.Size([2, 2, 1])

## Repeat

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c8a1762a-62b2-46cf-95c0-ea77984dacfd' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>