# Node Statistics on Graph

In [5]:
import numpy as np

# Centrality

In [6]:
node_ct = 5

In [7]:
adj_mat_rnd = np.random.randint(2, size=(node_ct, node_ct))
np.fill_diagonal(adj_mat_rnd, 0)
adj_mat_rnd = np.floor((adj_mat_rnd + adj_mat_rnd.T)/2)
adj_mat_rnd

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.]])

In [8]:
adj_mat = adj_mat_rnd

In [9]:
np.linalg.eig(adj_mat)

(array([-1.41421356e+00,  9.77950360e-17,  1.41421356e+00,  0.00000000e+00,
         0.00000000e+00]),
 array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  1.00000000e+00],
        [ 5.00000000e-01, -7.07106781e-01,  5.00000000e-01,
          0.00000000e+00,  0.00000000e+00],
        [ 5.00000000e-01,  7.07106781e-01,  5.00000000e-01,
          0.00000000e+00,  0.00000000e+00],
        [-7.07106781e-01,  9.02056208e-17,  7.07106781e-01,
          0.00000000e+00,  0.00000000e+00]]))

In [10]:
e_init = np.ones(node_ct)
e_init

array([1., 1., 1., 1., 1.])

In [11]:
np.matmul(adj_mat, e_init)

array([0., 0., 1., 1., 2.])

In [12]:
e_i = e_init.copy()

for i in range(5):
    e_i = np.matmul(adj_mat, e_i)
    # e_i = e_i/np.linalg.norm(e_i)
    print(e_i.shape)
    print(f"{i}: {e_i}")


(5,)
0: [0. 0. 1. 1. 2.]
(5,)
1: [0. 0. 2. 2. 2.]
(5,)
2: [0. 0. 2. 2. 4.]
(5,)
3: [0. 0. 4. 4. 4.]
(5,)
4: [0. 0. 4. 4. 8.]


In [13]:
def power_iteration(A, num_simulations: int):
    # Ideally choose a random vector
    # To decrease the chance that our vector
    # Is orthogonal to the eigenvector
    b_k = np.random.rand(A.shape[1])

    for _ in range(num_simulations):
        # calculate the matrix-by-vector product Ab
        b_k1 = np.dot(A, b_k)

        # calculate the norm
        b_k1_norm = np.linalg.norm(b_k1)

        # re normalize the vector
        b_k = b_k1 / b_k1_norm

    return b_k



In [14]:
power_iteration(np.array([[0.5, 0.5], [0.2, 0.8]]), 100)

array([0.70710678, 0.70710678])

In [15]:
power_iteration(adj_mat, 500)

array([0.        , 0.        , 0.61279393, 0.61279393, 0.49896612])

In [16]:
adj_florentine = np.array(
    [
        []
    ]
)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c8a1762a-62b2-46cf-95c0-ea77984dacfd' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>